# Generated by Django 5.2.6 on 2025-09-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.BooleanField(default=True, verbose_name='Notificaciones por Email')),
                ('push', models.BooleanField(default=True, verbose_name='Notificaciones Push')),
                ('sms', models.BooleanField(default=False, verbose_name='Notificaciones SMS')),
                ('reservas', models.BooleanField(default=True, verbose_name='Notificaciones de Reservas')),
                ('servicios', models.BooleanField(default=True, verbose_name='Notificaciones de Servicios')),
                ('promociones', models.BooleanField(default=True, verbose_name='Notificaciones de Promociones')),
                ('puntos', models.BooleanField(default=True, verbose_name='Notificaciones de Puntos')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_notificaciones', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RC', 'Reserva Creada'), ('RF', 'Reserva Confirmada'), ('RA', 'Reserva Cancelada'), ('SI', 'Servicio Iniciado'), ('SF', 'Servicio Finalizado'), ('PR', 'Promoción'), ('PA', 'Puntos Acumulados'), ('PR', 'Puntos Redimidos'), ('OT', 'Otro')], max_length=2, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
