# Generated by Django 4.2.11 on 2025-09-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_notificacion_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('RC', 'Reserva Creada'), ('RF', 'Reserva Confirmada'), ('RA', 'Reserva Cancelada'), ('SI', 'Servicio Iniciado'), ('SF', 'Servicio Finalizado'), ('CR', 'Calificación Recibida'), ('SA', 'Servicio Asignado'), ('PR', 'Promoción'), ('PA', 'Puntos Acumulados'), ('PR', 'Puntos Redimidos'), ('OT', 'Otro')], max_length=2, verbose_name='Tipo'),
        ),
    ]
