# Generated by Django 4.2.11 on 2025-09-26 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20250910_2314'),
        ('empleados', '0009_alter_calificacion_unique_together_and_more'),
        ('notificaciones', '0003_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='empleados.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='clientes.cliente', verbose_name='Cliente'),
        ),
    ]
