# Generated by Django 5.2.6 on 2025-09-04 23:38

import autenticacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=autenticacion.models.user_profile_image_path, verbose_name='Foto de Perfil'),
        ),
    ]
