# Generated by Django 4.2.11 on 2025-09-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin_sistema', 'Administrador del Sistema'), ('admin_autolavado', 'Administrador del Autolavado'), ('gerente', 'Gerente'), ('empleado', 'Empleado'), ('cliente', 'Cliente')], default='cliente', max_length=20, verbose_name='Rol'),
        ),
    ]
