# Generated by Django 4.2.11 on 2025-09-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
