# Generated by Django 4.2.11 on 2025-09-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_remove_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin_sistema', 'Administrador del Sistema'), ('admin_autolavado', 'Administrador de Autolavado'), ('gerente', 'Gerente'), ('lavador', 'Lavador'), ('cliente', 'Cliente')], default='cliente', max_length=20, verbose_name='Rol'),
        ),
    ]
