# Generated by Django 4.2.11 on 2025-09-28 20:44

import autolavados_plataforma.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('totp_secret', autolavados_plataforma.models.EncryptedCharField(blank=True, max_length=255)),
                ('backup_codes', models.JSONField(default=list)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('last_failed_login', models.DateTimeField(blank=True, null=True)),
                ('account_locked_until', models.DateTimeField(blank=True, null=True)),
                ('max_concurrent_sessions', models.IntegerField(default=3)),
                ('session_timeout_minutes', models.IntegerField(default=60)),
                ('notify_login_from_new_device', models.BooleanField(default=True)),
                ('notify_password_change', models.BooleanField(default=True)),
                ('notify_suspicious_activity', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', autolavados_plataforma.models.EncryptedTextField()),
                ('description', models.TextField(blank=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('INVESTIGATING', 'Investigando'), ('CONTAINED', 'Contenido'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=15)),
                ('affected_systems', models.JSONField(default=list)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('backup_type', models.CharField(choices=[('FULL', 'Completo'), ('INCREMENTAL', 'Incremental'), ('DIFFERENTIAL', 'Diferencial')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('file_path', autolavados_plataforma.models.EncryptedCharField(max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('encrypted', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Exitoso'), ('LOGIN_FAILED', 'Login Fallido'), ('LOGIN_BLOCKED', 'Login Bloqueado'), ('PASSWORD_CHANGE', 'Cambio de Contraseña'), ('PERMISSION_DENIED', 'Permiso Denegado'), ('SUSPICIOUS_ACTIVITY', 'Actividad Sospechosa'), ('DATA_ACCESS', 'Acceso a Datos'), ('DATA_MODIFICATION', 'Modificación de Datos'), ('ADMIN_ACTION', 'Acción de Administrador'), ('SYSTEM_ERROR', 'Error del Sistema')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='LOW', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='autolavados_timesta_2a6626_idx'), models.Index(fields=['event_type'], name='autolavados_event_t_7083c3_idx'), models.Index(fields=['severity'], name='autolavados_severit_131322_idx'), models.Index(fields=['user'], name='autolavados_user_id_1a2a05_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('FAILED_LOGIN', 'Intento de Login Fallido'), ('PASSWORD_CHANGE', 'Cambio de Contraseña'), ('PERMISSION_CHANGE', 'Cambio de Permisos'), ('DATA_ACCESS', 'Acceso a Datos'), ('DATA_MODIFICATION', 'Modificación de Datos'), ('SYSTEM_CONFIG', 'Configuración del Sistema'), ('SECURITY_VIOLATION', 'Violación de Seguridad'), ('BACKUP_CREATED', 'Backup Creado'), ('BACKUP_RESTORED', 'Backup Restaurado')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('resource', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('risk_level', models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], default='LOW', max_length=10)),
                ('success', models.BooleanField(default=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='autolavados_timesta_13b4cf_idx'), models.Index(fields=['event_type'], name='autolavados_event_t_71e6ff_idx'), models.Index(fields=['user'], name='autolavados_user_id_4ea943_idx'), models.Index(fields=['ip_address'], name='autolavados_ip_addr_6f26ec_idx'), models.Index(fields=['risk_level'], name='autolavados_risk_le_f66e44_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW', 'Ver'), ('LOGIN', 'Iniciar Sesión'), ('LOGOUT', 'Cerrar Sesión')], max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='autolavados_timesta_17b3df_idx'), models.Index(fields=['user'], name='autolavados_user_id_e62ad7_idx'), models.Index(fields=['action'], name='autolavados_action_38a86f_idx'), models.Index(fields=['model_name'], name='autolavados_model_n_43a990_idx')],
            },
        ),
    ]
