# Generated by Django 4.2.11 on 2025-09-11 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0018_reserva_precio_final_reserva_recompensa_aplicada'),
        ('clientes', '0002_auto_20250910_2314'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('PA', 'Pasaporte'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=2, verbose_name='Tipo de Documento')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('cargo', models.CharField(choices=[('LAV', 'Lavador'), ('SEC', 'Secador'), ('SUP', 'Supervisor'), ('CAJ', 'Cajero')], max_length=3, verbose_name='Cargo')),
                ('fecha_contratacion', models.DateField(verbose_name='Fecha de Contratación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='RegistroTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Finalización')),
                ('duracion_minutos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración en Minutos')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_tiempo', to='empleados.empleado', verbose_name='Empleado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_tiempo', to='reservas.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Registro de Tiempo',
                'verbose_name_plural': 'Registros de Tiempo',
                'ordering': ['-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Incentivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Incentivo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('fecha_otorgado', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Otorgado')),
                ('periodo_inicio', models.DateField(verbose_name='Inicio del Período')),
                ('periodo_fin', models.DateField(verbose_name='Fin del Período')),
                ('promedio_calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Promedio de Calificación')),
                ('servicios_completados', models.PositiveIntegerField(default=0, verbose_name='Servicios Completados')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentivos', to='empleados.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Incentivo',
                'verbose_name_plural': 'Incentivos',
                'ordering': ['-fecha_otorgado'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(help_text='Calificación de 1 a 5 estrellas', verbose_name='Puntuación')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Calificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to='clientes.cliente', verbose_name='Cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='empleados.empleado', verbose_name='Empleado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_empleado', to='reservas.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-fecha_calificacion'],
                'unique_together': {('empleado', 'servicio', 'cliente')},
            },
        ),
    ]
