# Generated by Django 4.2.11 on 2025-09-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/fotografias/', verbose_name='Fotografía'),
        ),
    ]
