# Generated by Django 4.2.11 on 2025-09-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_fotografia'),
        ('empleados', '0003_modify_empleado_model'),
    ]

    operations = [
    ]
