# Generated by Django 4.2.11 on 2025-09-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_merge_20250911_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='disponible',
            field=models.BooleanField(default=False, verbose_name='Disponible'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('lavador', 'Lavador'), ('administrativo', 'Administrativo'), ('supervisor', 'Supervisor'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Rol'),
        ),
    ]
