# Generated by Django 4.2.11 on 2025-09-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_empleado_disponible_empleado_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='email_personal',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Personal'),
        ),
    ]
