# Generated by Django 4.2.11 on 2025-09-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_bonificacionganada_historialredenciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionbonificacion',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='historialredenciones',
            name='bonificacion',
        ),
        migrations.RemoveField(
            model_name='historialredenciones',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='historialredenciones',
            name='procesado_por',
        ),
        migrations.DeleteModel(
            name='BonificacionGanada',
        ),
        migrations.DeleteModel(
            name='ConfiguracionBonificacion',
        ),
        migrations.DeleteModel(
            name='HistorialRedenciones',
        ),
    ]
