# Generated by Django 4.2.11 on 2025-09-26 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0024_bahia_activa_produccion_bahia_ip_publica_and_more'),
        ('clientes', '0002_auto_20250910_2314'),
        ('empleados', '0008_remove_configuracionbonificacion_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='reservas.reserva', verbose_name='Reserva'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('reserva', 'cliente')},
        ),
    ]
