# Generated by Django 4.2.11 on 2025-10-03 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleados', '0010_configuracionbonificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentivo',
            name='cobrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonificaciones_tramitadas', to=settings.AUTH_USER_MODEL, verbose_name='Cobrado por'),
        ),
        migrations.AddField(
            model_name='incentivo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cobrada', 'Cobrada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='incentivo',
            name='fecha_cobro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cobro'),
        ),
    ]
