# Generated by Django 4.2.11 on 2025-10-14 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleados', '0011_add_estado_to_incentivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Bonificación')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('dias_consecutivos_requeridos', models.PositiveIntegerField(default=0, help_text='Número de días consecutivos que debe trabajar el empleado', verbose_name='Días Consecutivos Requeridos')),
                ('servicios_requeridos', models.PositiveIntegerField(default=0, help_text='Cantidad mínima de servicios que debe realizar', verbose_name='Servicios Requeridos')),
                ('calificacion_minima', models.DecimalField(decimal_places=2, default=0.0, help_text='Calificación promedio mínima requerida (ej: 4.50)', max_digits=3, verbose_name='Calificación Mínima')),
                ('monto_bonificacion', models.DecimalField(decimal_places=2, help_text='Monto en pesos que se otorgará al empleado', max_digits=10, verbose_name='Monto de Bonificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonificaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Bonificación',
                'verbose_name_plural': 'Bonificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='BonificacionObtenida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_periodo', models.DateField(verbose_name='Inicio del Período')),
                ('fecha_fin_periodo', models.DateField(verbose_name='Fin del Período')),
                ('dias_consecutivos_trabajados', models.PositiveIntegerField(verbose_name='Días Consecutivos Trabajados')),
                ('servicios_realizados', models.PositiveIntegerField(verbose_name='Servicios Realizados')),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Calificación Promedio')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Redimir'), ('redimida', 'Redimida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_obtencion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Obtención')),
                ('fecha_redencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Redención')),
                ('notas_redencion', models.TextField(blank=True, verbose_name='Notas de Redención')),
                ('bonificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonificaciones_otorgadas', to='empleados.bonificacion', verbose_name='Bonificación')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonificaciones_obtenidas', to='empleados.empleado', verbose_name='Empleado')),
                ('redimida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonificaciones_redimidas', to=settings.AUTH_USER_MODEL, verbose_name='Redimida por')),
            ],
            options={
                'verbose_name': 'Bonificación Obtenida',
                'verbose_name_plural': 'Bonificaciones Obtenidas',
                'ordering': ['-fecha_obtencion'],
                'unique_together': {('empleado', 'bonificacion', 'fecha_inicio_periodo', 'fecha_fin_periodo')},
            },
        ),
    ]
