# Generated by Django 4.2.11 on 2025-10-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0012_bonificacion_bonificacionobtenida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonificacion',
            name='calificacion_minima',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Calificación promedio mínima requerida (dejar en 0 para ignorar este criterio)', max_digits=3, null=True, verbose_name='Calificación Mínima'),
        ),
        migrations.AlterField(
            model_name='bonificacion',
            name='dias_consecutivos_requeridos',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Número de días consecutivos que debe trabajar el empleado (dejar en 0 para ignorar este criterio)', null=True, verbose_name='Días Consecutivos Requeridos'),
        ),
        migrations.AlterField(
            model_name='bonificacion',
            name='servicios_requeridos',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Cantidad mínima de servicios que debe realizar (dejar en 0 para ignorar este criterio)', null=True, verbose_name='Servicios Requeridos'),
        ),
    ]
