# Generated by Django 4.2.11 on 2025-10-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaGerencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('baja_ocupacion', 'Baja Ocupación'), ('bajo_rendimiento', 'Empleado con Bajo Rendimiento'), ('cliente_insatisfecho', 'Cliente Insatisfecho'), ('meta_ingresos', 'Meta de Ingresos')], max_length=30, verbose_name='Tipo de Alerta')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
            ],
            options={
                'verbose_name': 'Alerta Gerencial',
                'verbose_name_plural': 'Alertas Gerenciales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionBonificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Bonificación')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('calificacion', 'Por Calificación Promedio'), ('servicios', 'Por Cantidad de Servicios'), ('puntualidad', 'Por Puntualidad'), ('ventas', 'Por Monto de Ventas')], max_length=20, verbose_name='Tipo de Bonificación')),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mínimo Requerido')),
                ('monto_bonificacion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Bonificación')),
                ('porcentaje_bonificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de Bonificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Configuración de Bonificación',
                'verbose_name_plural': 'Configuraciones de Bonificación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetricaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('total_reservas', models.PositiveIntegerField(default=0, verbose_name='Total Reservas')),
                ('reservas_completadas', models.PositiveIntegerField(default=0, verbose_name='Reservas Completadas')),
                ('reservas_canceladas', models.PositiveIntegerField(default=0, verbose_name='Reservas Canceladas')),
                ('ingresos_dia', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ingresos del Día')),
                ('nuevos_clientes', models.PositiveIntegerField(default=0, verbose_name='Nuevos Clientes')),
                ('servicios_por_empleado', models.JSONField(default=dict, verbose_name='Servicios por Empleado')),
                ('calificacion_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Calificación Promedio')),
                ('fecha_calculo', models.DateTimeField(auto_now=True, verbose_name='Fecha de Cálculo')),
            ],
            options={
                'verbose_name': 'Métrica de Negocio',
                'verbose_name_plural': 'Métricas de Negocio',
                'ordering': ['-fecha'],
                'unique_together': {('fecha',)},
            },
        ),
    ]
