# Generated by Django 4.2.11 on 2025-10-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_gerente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('query_sql', models.TextField(verbose_name='Query SQL')),
                ('tipo_grafico', models.CharField(choices=[('line', 'Línea'), ('bar', 'Barras'), ('pie', 'Circular'), ('doughnut', 'Dona'), ('area', 'Área')], default='bar', max_length=20, verbose_name='Tipo de Gráfico')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Métrica Personalizada',
                'verbose_name_plural': 'Métricas Personalizadas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.DeleteModel(
            name='AlertaGerencial',
        ),
        migrations.DeleteModel(
            name='MetricaNegocio',
        ),
        migrations.AlterModelOptions(
            name='configuracionbonificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Configuración de Bonificación', 'verbose_name_plural': 'Configuraciones de Bonificaciones'},
        ),
        migrations.RemoveField(
            model_name='configuracionbonificacion',
            name='monto_bonificacion',
        ),
        migrations.RemoveField(
            model_name='configuracionbonificacion',
            name='porcentaje_bonificacion',
        ),
        migrations.RemoveField(
            model_name='configuracionbonificacion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='configuracionbonificacion',
            name='valor_minimo',
        ),
        migrations.AddField(
            model_name='configuracionbonificacion',
            name='calificacion_minima',
            field=models.DecimalField(decimal_places=2, default=4.5, help_text='Calificación promedio mínima requerida (1-5)', max_digits=3, verbose_name='Calificación Mínima'),
        ),
        migrations.AddField(
            model_name='configuracionbonificacion',
            name='monto_fijo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto fijo de bonificación', max_digits=10, null=True, verbose_name='Monto Fijo'),
        ),
        migrations.AddField(
            model_name='configuracionbonificacion',
            name='periodo',
            field=models.CharField(choices=[('M', 'Mensual'), ('Q', 'Quincenal'), ('S', 'Semanal')], default='M', max_length=1, verbose_name='Período de Evaluación'),
        ),
        migrations.AddField(
            model_name='configuracionbonificacion',
            name='porcentaje_servicios',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje del valor total de servicios realizados', max_digits=5, null=True, verbose_name='Porcentaje por Servicios'),
        ),
        migrations.AddField(
            model_name='configuracionbonificacion',
            name='servicios_minimos',
            field=models.PositiveIntegerField(default=50, help_text='Cantidad mínima de servicios completados en el período', verbose_name='Servicios Mínimos'),
        ),
    ]
