# Generated by Django 4.2.11 on 2025-10-08 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_gerente', '0002_metricapersonalizada_delete_alertagerencial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('entidad', models.CharField(choices=[('clientes', 'Clientes'), ('servicios', 'Servicios'), ('empleados', 'Empleados'), ('ingresos', 'Ingresos')], max_length=20)),
                ('metrica', models.CharField(choices=[('count', 'Conteo'), ('sum', 'Suma'), ('avg', 'Promedio'), ('max', 'Máximo'), ('min', 'Mínimo')], max_length=20)),
                ('campo', models.CharField(help_text='Nombre del campo sobre el que se aplica la métrica (ej: Reserva.precio_final)', max_length=100)),
                ('estado_filtro', models.CharField(blank=True, help_text='Opcional: filtrar por estado (ej: completada, cancelada)', max_length=30, null=True)),
                ('periodo_dias', models.PositiveIntegerField(default=30, help_text='Rango en días para calcular la métrica')),
                ('umbral_alerta', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional: umbral para generar alertas', max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis_configurados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración KPI',
                'verbose_name_plural': 'Configuraciones KPI',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.DeleteModel(
            name='ConfiguracionBonificacion',
        ),
        migrations.DeleteModel(
            name='MetricaPersonalizada',
        ),
    ]
