# Generated by Django 4.2.11 on 2025-10-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_gerente', '0003_kpiconfiguracion_delete_configuracionbonificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiconfiguracion',
            name='entidad',
            field=models.CharField(choices=[('clientes', 'Clientes'), ('servicios', 'Servicios'), ('empleados', 'Empleados'), ('ingresos', 'Ingresos'), ('reservas', 'Reservas')], max_length=20),
        ),
    ]
