# Generated by Django 4.2.11 on 2025-09-07 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_horariodisponible_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bahia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Bahía',
                'verbose_name_plural': 'Bahías',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_reserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='bahia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reservas.bahia', verbose_name='Bahía'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('fecha_hora', 'bahia'), name='unique_reserva_bahia'),
        ),
    ]
