# Generated by Django 4.2.11 on 2025-09-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_bahia_remove_reserva_unique_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahia',
            name='codigo_qr',
            field=models.ImageField(blank=True, null=True, upload_to='bahias/qr/', verbose_name='Código QR'),
        ),
        migrations.AddField(
            model_name='bahia',
            name='ip_camara',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IP de la Cámara'),
        ),
        migrations.AddField(
            model_name='bahia',
            name='tiene_camara',
            field=models.BooleanField(default=False, verbose_name='Tiene Cámara Web'),
        ),
    ]
