# Generated by Django 4.2.11 on 2025-09-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_mediopago_reserva_medio_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='stream_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Token de Transmisión'),
        ),
    ]
