# Generated by Django 4.2.11 on 2025-09-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_reserva_stream_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediopago',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key'),
        ),
        migrations.AddField(
            model_name='mediopago',
            name='api_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Secret'),
        ),
        migrations.AddField(
            model_name='mediopago',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Comercio'),
        ),
        migrations.AddField(
            model_name='mediopago',
            name='sandbox',
            field=models.BooleanField(default=True, verbose_name='Modo Sandbox'),
        ),
        migrations.AlterField(
            model_name='mediopago',
            name='tipo',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('TA', 'Tarjeta'), ('TR', 'Transferencia'), ('PU', 'Puntos'), ('WO', 'Wompi'), ('PY', 'PayU'), ('EP', 'ePayco'), ('NQ', 'Nequi'), ('PS', 'PSE')], default='EF', max_length=2, verbose_name='Tipo'),
        ),
    ]
