# Generated by Django 4.2.11 on 2025-09-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_mediopago_api_key_mediopago_api_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='referencia_pago',
            field=models.CharField(blank=True, help_text='Referencia única para el pago en pasarelas', max_length=100, null=True, verbose_name='Referencia de Pago'),
        ),
    ]
