# Generated by Django 4.2.11 on 2025-09-08 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_reserva_referencia_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reservas.vehiculo', verbose_name='Vehículo'),
        ),
    ]
