# Generated by Django 4.2.11 on 2025-09-08 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('reservas', '0009_reserva_vehiculo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiculo',
            unique_together={('cliente', 'placa')},
        ),
    ]
