# Generated by Django 4.2.11 on 2025-09-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_alter_vehiculo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('CO', 'Confirmada'), ('PR', 'En Proceso'), ('CM', 'Completada'), ('CA', 'Cancelada'), ('IN', 'Incumplida')], default='PE', max_length=2, verbose_name='Estado'),
        ),
    ]
