# Generated by Django 4.2.11 on 2025-09-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_inicio_servicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio del Servicio'),
        ),
    ]
