# Generated by Django 4.2.11 on 2025-09-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_reserva_fecha_inicio_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('disponible', models.BooleanField(default=False, help_text='Indica si el lavadero estará disponible en esta fecha', verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Fecha Especial',
                'verbose_name_plural': 'Fechas Especiales',
                'ordering': ['fecha'],
            },
        ),
        migrations.AlterField(
            model_name='disponibilidadhoraria',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si este horario está disponible para reservas', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='disponibilidadhoraria',
            name='capacidad_maxima',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número máximo de vehículos que pueden ser atendidos simultáneamente en este horario', verbose_name='Capacidad Máxima'),
        ),
    ]
