# Generated by Django 4.2.11 on 2025-09-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_fechaespecial_alter_disponibilidadhoraria_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechaespecial',
            options={'ordering': ['fecha'], 'verbose_name': 'Estado de Servicios por Fecha', 'verbose_name_plural': 'Estados de Servicios por Fecha'},
        ),
        migrations.AddField(
            model_name='fechaespecial',
            name='capacidad',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número máximo de vehículos que pueden ser atendidos simultáneamente en esta fecha', verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='fechaespecial',
            name='hora_fin',
            field=models.TimeField(blank=True, help_text='Hora de fin de servicios para esta fecha especial', null=True, verbose_name='Hora de Fin'),
        ),
        migrations.AddField(
            model_name='fechaespecial',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Hora de inicio de servicios para esta fecha especial', null=True, verbose_name='Hora de Inicio'),
        ),
    ]
