# Generated by Django 4.2.11 on 2025-09-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0014_alter_fechaespecial_options_fechaespecial_capacidad_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiculo',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(fields=('placa',), name='unique_placa_vehiculo'),
        ),
    ]
