# Generated by Django 4.2.11 on 2025-09-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_alter_vehiculo_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahia',
            name='tipo_camara',
            field=models.CharField(blank=True, choices=[('droidcam', 'DroidCam'), ('ipwebcam', 'IP Webcam'), ('iriun', 'Iriun Webcam'), ('rtsp', 'Cámara RTSP'), ('http', 'Cámara HTTP'), ('otro', 'Otro tipo de cámara')], default='ipwebcam', max_length=20, null=True, verbose_name='Tipo de Cámara'),
        ),
        migrations.AlterField(
            model_name='bahia',
            name='ip_camara',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL/IP de la Cámara'),
        ),
    ]
