# Generated by Django 4.2.11 on 2025-09-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0016_bahia_tipo_camara_alter_bahia_ip_camara'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto de descuento aplicado por redención de puntos', max_digits=10, verbose_name='Descuento Aplicado'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='puntos_redimidos',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de puntos redimidos para esta reserva', verbose_name='Puntos Redimidos'),
        ),
    ]
