# Generated by Django 4.2.11 on 2025-09-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0017_reserva_descuento_aplicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='precio_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Final'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='recompensa_aplicada',
            field=models.CharField(blank=True, max_length=100, verbose_name='Recompensa Aplicada'),
        ),
    ]
