# Generated by Django 4.2.11 on 2025-09-11 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0018_reserva_precio_final_reserva_recompensa_aplicada'),
    ]

    operations = [
        # Campo eliminado debido a la implementación de asignación automática
        # migrations.AddField(
        #     model_name='reserva',
        #     name='lavador',
        #     field=models.ForeignKey(blank=True, help_text='Lavador asignado para realizar el servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_asignadas', to='empleados.empleado', verbose_name='Lavador'),
        # ),
    ]
