# Generated by Django 4.2.11 on 2025-09-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0019_reserva_lavador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FechaEspecial',
        ),
    ]
