# Generated by Django 4.2.11 on 2025-09-12 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_empleado_disponible_empleado_rol'),
        ('reservas', '0020_delete_fechaespecial'),
    ]

    operations = [
        # No operations needed as the fields already exist in the database
        # This migration is just to keep the migration history consistent
        
    ]
