# Generated by Django 4.2.11 on 2025-09-19 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_empleado_email_personal'),
        ('reservas', '0021_reserva_asignacion_automatica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='asignacion_automatica',
            field=models.BooleanField(default=True, help_text='Indica si el lavador fue asignado automáticamente o seleccionado por el cliente', verbose_name='Asignación Automática'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='calificacion_solicitada',
            field=models.BooleanField(default=False, help_text='Indica si se ha enviado la solicitud de calificación al cliente', verbose_name='Calificación Solicitada'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='lavador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_asignadas', to='empleados.empleado', verbose_name='Lavador'),
        ),
    ]
