# Generated by Django 4.2.11 on 2025-09-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0022_reserva_asignacion_automatica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediopago',
            name='account_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Account ID'),
        ),
        migrations.AddField(
            model_name='mediopago',
            name='base_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Base'),
        ),
        migrations.AddField(
            model_name='mediopago',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='mediopago',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Secret'),
        ),
        migrations.AddField(
            model_name='mediopago',
            name='public_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public Key'),
        ),
        migrations.AddField(
            model_name='mediopago',
            name='webhook_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Webhook'),
        ),
    ]
