# Generated by Django 4.2.11 on 2025-09-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0023_mediopago_account_id_mediopago_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahia',
            name='activa_produccion',
            field=models.BooleanField(default=False, help_text='Usar configuración de producción (IP pública) en lugar de local', verbose_name='Activa en Producción'),
        ),
        migrations.AddField(
            model_name='bahia',
            name='ip_publica',
            field=models.CharField(blank=True, help_text='IP pública o dominio para acceso desde internet', max_length=200, null=True, verbose_name='IP Pública/Dominio'),
        ),
        migrations.AddField(
            model_name='bahia',
            name='password_camara',
            field=models.CharField(blank=True, help_text='Contraseña para autenticación (si es requerido)', max_length=100, null=True, verbose_name='Contraseña de la Cámara'),
        ),
        migrations.AddField(
            model_name='bahia',
            name='puerto_externo',
            field=models.PositiveIntegerField(blank=True, help_text='Puerto configurado en el router para acceso externo', null=True, verbose_name='Puerto Externo'),
        ),
        migrations.AddField(
            model_name='bahia',
            name='usar_ssl',
            field=models.BooleanField(default=False, help_text='Marcar si la cámara usa conexión segura', verbose_name='Usar HTTPS/SSL'),
        ),
        migrations.AddField(
            model_name='bahia',
            name='usuario_camara',
            field=models.CharField(blank=True, help_text='Usuario para autenticación (si es requerido)', max_length=50, null=True, verbose_name='Usuario de la Cámara'),
        ),
    ]
