# Generated by Django 4.2.11 on 2025-10-01 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0009_alter_calificacion_unique_together_and_more'),
        ('reservas', '0024_bahia_activa_produccion_bahia_ip_publica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del dispositivo')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='ID del dispositivo')),
                ('sim_number', models.CharField(max_length=20, verbose_name='Número SIM')),
                ('imei', models.CharField(blank=True, max_length=20, verbose_name='IMEI')),
                ('servidor_gps', models.CharField(default='localhost', max_length=255, verbose_name='Servidor GPS')),
                ('puerto_gps', models.PositiveIntegerField(default=5023, verbose_name='Puerto GPS')),
                ('protocolo', models.CharField(default='GT06', max_length=20, verbose_name='Protocolo')),
                ('activo', models.BooleanField(default=True)),
                ('en_uso', models.BooleanField(default=False)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('nivel_bateria', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('intervalo_reporte', models.PositiveIntegerField(default=30, verbose_name='Intervalo de reporte (segundos)')),
                ('velocidad_maxima', models.PositiveIntegerField(default=80, verbose_name='Velocidad máxima permitida (km/h)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración GPS',
                'verbose_name_plural': 'Configuraciones GPS',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_recogida', models.TextField(verbose_name='Dirección de recogida')),
                ('latitud_recogida', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud_recogida', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('direccion_entrega', models.TextField(blank=True, verbose_name='Dirección de entrega')),
                ('latitud_entrega', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud_entrega', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('confirmado', 'Confirmado'), ('en_ruta_recogida', 'En ruta a recogida'), ('vehiculo_recogido', 'Vehículo recogido'), ('en_ruta_lavadero', 'En ruta al lavadero'), ('en_lavadero', 'En el lavadero'), ('lavado_iniciado', 'Lavado iniciado'), ('lavado_completado', 'Lavado completado'), ('en_ruta_entrega', 'En ruta a entrega'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20)),
                ('gps_device_id', models.CharField(blank=True, max_length=100, verbose_name='ID del dispositivo GPS')),
                ('gps_sim_number', models.CharField(blank=True, max_length=20, verbose_name='Número SIM del GPS')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_recogida', models.DateTimeField(blank=True, null=True)),
                ('fecha_llegada_lavadero', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('costo_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notas_cliente', models.TextField(blank=True, verbose_name='Notas del cliente')),
                ('notas_empleado', models.TextField(blank=True, verbose_name='Notas del empleado')),
                ('empleado_conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_domicilio', to='empleados.empleado')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servicio_domicilio', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Servicio a Domicilio',
                'verbose_name_plural': 'Servicios a Domicilio',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cambio_estado', 'Cambio de estado'), ('llegada_recogida', 'Llegada a punto de recogida'), ('vehiculo_recogido', 'Vehículo recogido'), ('llegada_lavadero', 'Llegada al lavadero'), ('lavado_iniciado', 'Lavado iniciado'), ('lavado_completado', 'Lavado completado'), ('en_ruta_entrega', 'En ruta a entrega'), ('vehiculo_entregado', 'Vehículo entregado'), ('retraso', 'Retraso en el servicio'), ('problema', 'Problema reportado')], max_length=20)),
                ('mensaje', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('enviado_automaticamente', models.BooleanField(default=False)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='notificaciones_domicilio/')),
                ('servicio_domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='reservas.serviciodomicilio')),
            ],
            options={
                'verbose_name': 'Notificación de Domicilio',
                'verbose_name_plural': 'Notificaciones de Domicilio',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GPSTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('velocidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Velocidad (km/h)')),
                ('direccion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Dirección (grados)')),
                ('altitud', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Altitud (m)')),
                ('precision', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Precisión (m)')),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nivel de batería (%)')),
                ('signal_strength', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Fuerza de señal')),
                ('servicio_domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='reservas.serviciodomicilio')),
            ],
            options={
                'verbose_name': 'Punto de Tracking GPS',
                'verbose_name_plural': 'Puntos de Tracking GPS',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['servicio_domicilio', '-timestamp'], name='reservas_gp_servici_b4f5e2_idx')],
            },
        ),
    ]
