# Generated by Django 4.2.11 on 2025-10-02 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0025_configuraciongps_serviciodomicilio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('DP', 'Descuento porcentual'), ('DM', 'Descuento por monto'), ('SG', 'Servicio gratis')], max_length=2, verbose_name='Tipo')),
                ('puntos_requeridos', models.PositiveIntegerField(default=0, verbose_name='Puntos requeridos')),
                ('valor_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor porcentaje')),
                ('valor_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor monto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompensas', to='reservas.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
                'ordering': ['servicio', 'puntos_requeridos', 'nombre'],
            },
        ),
        migrations.DeleteModel(
            name='ConfiguracionGPS',
        ),
        migrations.RemoveField(
            model_name='notificaciondomicilio',
            name='servicio_domicilio',
        ),
        migrations.RemoveField(
            model_name='serviciodomicilio',
            name='empleado_conductor',
        ),
        migrations.RemoveField(
            model_name='serviciodomicilio',
            name='reserva',
        ),
        migrations.DeleteModel(
            name='GPSTracking',
        ),
        migrations.DeleteModel(
            name='NotificacionDomicilio',
        ),
        migrations.DeleteModel(
            name='ServicioDomicilio',
        ),
    ]
