# Generated by Django 4.2.11 on 2025-10-05 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0011_add_estado_to_incentivo'),
        ('reservas', '0026_recompensa_delete_configuraciongps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='empleado_finalizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_finalizados', to='empleados.empleado', verbose_name='Empleado que finalizó el servicio'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='empleado_inicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_iniciados', to='empleados.empleado', verbose_name='Empleado que inició el servicio'),
        ),
    ]
