# Generated by Django 4.2.11 on 2025-10-10 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0011_add_estado_to_incentivo'),
        ('reservas', '0027_reserva_empleado_finalizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='empleado_finalizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_finalizadas', to='empleados.empleado', verbose_name='Empleado que finalizó'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='empleado_inicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_iniciadas', to='empleados.empleado', verbose_name='Empleado que inició'),
        ),
    ]
